{% set name = "gsshapy" %}
{% set version = "2.3.9" %}
{% set sha256 = "13b47b450d0cc5e9053b83211dac8cf2905991a1626bda7c6e9219a7e70ceb50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  skip: True  # [py2k]

requirements:
  build:
    - pip
    - python
    - setuptools
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - affine
    - appdirs
    - gdal
    - geopandas
    - mapkit>=1.2.6
    - pangaea
    - psycopg2
    - pynio          # [not win and not py3k]
    - pyyaml
    - rapidpy
    - timezonefinder
    - utm
    - wrf-python

test:
  imports:
    - gsshapy
    - gsshapy.orm
    - gsshapy.orm.file_io
    - gsshapy.orm.prj
    - gsshapy.lib
    - gsshapy.lib.db_tools
    - gsshapy.grid
    - gsshapy.grid.grid_to_gssha
    - gsshapy.grid.hrrr_to_gssha
    - gsshapy.grid.era_to_gssha
    - gsshapy.grid.nwm_to_gssha
    - gsshapy.modeling
    - gsshapy.modeling.event
    - gsshapy.modeling.framework
    - gsshapy.modeling.model

about:
  home: http://github.com/ci-water/gsshapy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Object Relational Model for GSSHA model files and a toolkit to convert gridded input into GSSHA input.'
  description: |
    GsshaPy is an object relational model (ORM) for the
    Gridded Surface Subsurface Hydrologic Analysis (GSSHA) model
    and a toolkit to convert gridded input into GSSHA input.
    The purpose of GsshaPy is to expose GSSHA files to a web
    development environment by reading them into an SQL database.
    The files can also be written back to file for model execution.
  doc_url: http://gsshapy.readthedocs.io
  dev_url: https://github.com/ci-water/gsshapy

extra:
  recipe-maintainers:
    - dharhas
    - kajiglet
    - sdc50
    - swainn
    - snowman2
