{% set name = "gsshapy" %}
{% set version = "2.3.8" %}
{% set sha256 = "dbf6bba974a66deb1e0522678b014b5ebe9a09142e60d6fdd42b41b0b4c9d3c1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - affine
    - appdirs
    - gdal
    - geopandas
    - mapkit
    - pangaea
    - psycopg2
    - pynio          # [not win and not py3k]
    - pyyaml
    - rapidpy
    - timezonefinder
    - utm
    - wrf-python

test:
  imports:
    - gsshapy
    - gsshapy.orm
    - gsshapy.orm.file_io
    - gsshapy.orm.prj
    - gsshapy.lib
    - gsshapy.lib.db_tools
    - gsshapy.grid
    - gsshapy.grid.grid_to_gssha
    - gsshapy.grid.hrrr_to_gssha
    - gsshapy.grid.era_to_gssha
    - gsshapy.grid.nwm_to_gssha
    - gsshapy.modeling
    - gsshapy.modeling.event
    - gsshapy.modeling.framework
    - gsshapy.modeling.model

about:
  home: http://github.com/ci-water/gsshapy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Object Relational Model for GSSHA model files and a toolkit to convert gridded input into GSSHA input.'
  description: |
    GsshaPy is an object relational model (ORM) for the
    Gridded Surface Subsurface Hydrologic Analysis (GSSHA) model
    and a toolkit to convert gridded input into GSSHA input.
    The purpose of GsshaPy is to expose GSSHA files to a web
    development environment by reading them into an SQL database.
    The files can also be written back to file for model execution.
  doc_url: http://gsshapy.readthedocs.io
  dev_url: https://github.com/ci-water/gsshapy

extra:
  recipe-maintainers:
    - dharhas
    - kajiglet
    - sdc50
    - swainn
    - snowman2
