travis:
  secure:
    BINSTAR_TOKEN: WvLn16HX3S8kL2sYRiPXt5gbFqFyqfD4eQ+zqEg1C0I9uJvCeldHGqqUQMzoysMXoCYV8rszs6goAxseLKNwO1PEyUIKAKhUEuwmeR5qCGox0duzmjy/zSaC7nEe8pHWSSeTNCtD9Buzcx1TsobaTZxl/PCgH1xy1Cu2RjTcGlygO63C3bh50zX/10iH+BMiFMr11pFLkLy+oHS/dQHy2AgNsPHoQ4K8vF4BOzgiewBaMZDN/GQCou2YNmrxKs8sgxxVmGLufIzpJH7cy//edFicyKGUPql1i0sN2yr4Nst0Dqq5ZlxstC6TvDmNHB4RqMwkw2kXrn2gfHz5se15kxQ8BxSeUb1pTPxgEwCr3GYUqwwVSMYyEGhkXLzJCHvIhghVbBd6AK2IQ0sAk+fcAGP3fqhJVcd/6QR5vfeN4cP0+TBWmExTZI/L2pSi/zer0u2hqL71BmK3md3qxCdI2tFxrMNKJggugrvMtpjjxQKCLeJc+uirgNr4EtYgNCEnWz3bFwP54Yrbb83KwLygMooBJOGZpGkSO5CmJhGn+LtUDMZdT6OjA8Hz46EmLhIFU/gVXfFMcYbc1bCEsckw0ww8da3JHXkUGmt73hi4J/QhoGqSxkHPHeUghH74hYKM6kf6IcYjrAE6cl/5BaQBGLabPvlZV/Ayz/Z44y9QfyE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
min_py_ver: "36"
